from django.db import models

class CardCategory(models.Model):
	name = models.CharField(max_length=30)
	image = models.ImageField()
	usad1 = models.IntegerField()
	usan1 = models.IntegerField()	
	usad2 = models.IntegerField()
	usan2 = models.IntegerField()	
	ukd1 = models.IntegerField()
	ukn1 = models.IntegerField()	
	ukd2 = models.IntegerField()
	ukn2 = models.IntegerField()
	eurd1 = models.IntegerField()
	eurn1 = models.IntegerField()	
	eurd2 = models.IntegerField()
	eurn2 = models.IntegerField()
	aud1 = models.IntegerField()
	aun1 = models.IntegerField()	
	aud2 = models.IntegerField()
	aun2 = models.IntegerField()
	cadd1 = models.IntegerField()
	cadn1 = models.IntegerField()	
	cadd2 = models.IntegerField()
	cadn2 = models.IntegerField()